WEBHOOK_URL_TEST = "https://germancapybara.app.n8n.cloud/webhook-test/4bdb11b9-6f5c-449e-a90c-d5bc77b23635"
WEBHOOK_URL_PROD = "https://germancapybara.app.n8n.cloud/webhook-test/4bdb11b9-6f5c-449e-a90c-d5bc77b23635"


